goog.provide('npf.dom.TagName');


/**
 * @enum {string}
 */
npf.dom.TagName = {
  ALT_GLYPH: 'altGlyph',
  ALT_GLYPH_DEF: 'altGlyphDef',
  ALT_GLYPH_ITEM: 'altGlyphItem',
  ANIMATE: 'animate',
  ANIMATE_COLOR: 'animateColor',
  ANIMATE_MOTION: 'animateMotion',
  ANIMATE_TRANSFORM: 'animateTransform',
  CIRCLE: 'circle',
  CLIP_PATH: 'clipPath',
  COLOR_PROFILE: 'color-profile',
  CURSOR: 'cursor',
  DEFINITION_SRC: 'definition-src',
  DEFS: 'defs',
  DESC: 'desc',
  ELLIPSE: 'ellipse',
  FE_BLEND: 'feBlend',
  FE_COLOR_MATRIX: 'feColorMatrix',
  FE_COMPONENT_TRANSFER: 'feComponentTransfer',
  FE_COMPOSITE: 'feComposite',
  FE_CONVOLVE_MATRIX: 'feConvolveMatrix',
  FE_DIFFUSE_LIGHTING: 'feDiffuseLighting',
  FE_DISPLACEMENT_MAP: 'feDisplacementMap',
  FE_DISTANT_LIGHT: 'feDistantLight',
  FE_BLOOD: 'feBlood',
  FE_FUNC_A: 'feFuncA',
  FE_FUNC_B: 'feFuncB',
  FE_FUNC_G: 'feFuncG',
  FE_FUNC_R: 'feFuncR',
  FE_GAUSSIAN_BLUR: 'feGaussianBlur',
  FE_IMAGE: 'feImage',
  FE_MERGE: 'feMerge',
  FE_MERGE_NODE: 'feMergeNode',
  FE_MORPHOLOGY: 'feMorphology',
  FE_OFFSET: 'feOffset',
  FE_POINT_LIGHT: 'fePointLight',
  FE_SPECULAR_LIGHTING: 'feSpecularLighting',
  FE_SPOT_LIGHT: 'feSpotLight',
  FE_TILE: 'feTile',
  FE_TURBULENCE: 'feTurbulence',
  FILTER: 'filter',
  FONT: 'font',
  FONT_FACE: 'font-face',
  FONT_FACE_FORMAT: 'font-face-format',
  FONT_FACE_NAME: 'font-face-name',
  FONT_FACE_SRC: 'font-face-src',
  FONT_FACE_URI: 'font-face-uri',
  FOREIGN_OBJECT: 'foreignObject',
  G: 'g',
  GLYPH: 'glyph',
  GLYPH_REF: 'glyphRef',
  HKERN: 'hkern',
  IMAGE: 'image',
  LINE: 'line',
  LINEAR_GRADIENT: 'linearGradient',
  MARKER: 'marker',
  MASK: 'mask',
  METADATA: 'metadata',
  MISSING_GLYPH: 'missing-glyph',
  MPATH: 'mpath',
  PATH: 'path',
  PATTERN: 'pattern',
  POLYGON: 'polygon',
  POLYLINE: 'polyline',
  RADIAL_GRADIENT: 'radialGradient',
  RECT: 'rect',
  SCRIPT: 'script',
  SET: 'set',
  STOP: 'stop',
  STYLE: 'style',
  SVG: 'svg',
  SWITCH: 'switch',
  SYMBOL: 'symbol',
  TEXT: 'text',
  TEXT_PATH: 'textPath',
  TITLE: 'title',
  TREF: 'tref',
  TSPAN: 'tspan',
  USE: 'use',
  VIEW: 'view',
  VKERN: 'vkern'
};
